[theme]
base = "light"
primaryColor = "#087F73"
backgroundColor = "#F6F8F8"
secondaryBackgroundColor = "#F2F7F6"
textColor = "#142126"
font = "sans-serif"

[server]
headless = true

[browser]
gatherUsageStats = false
