[theme]
base = "light"
primaryColor = "#20A464"
backgroundColor = "#F5F5F7"
secondaryBackgroundColor = "#F0F4F8"
textColor = "#1D1D1F"
font = "sans-serif"

[server]
headless = true

[browser]
gatherUsageStats = false
